export const vocabulariesTestRange = "범위: Day11 11번 - Day11 30번";
export const vocabularies = [
    { vocabulary: 'reward', meaning: 'v.보답하다<br/>n.보상,포상' },
    { vocabulary: 'contain', meaning: 'v.(그릇,장소에)포함하다, 들어있다' },
    { vocabulary: 'detailed', meaning: 'adj.세부적인, 상세한' },
    { vocabulary: 'warn', meaning: 'v.경고하다' },
    { vocabulary: 'attempt', meaning: 'v.시도하다<br/>n.시도,기도' },
    { vocabulary: 'option', meaning: 'n.선택(권),선택지' },
    { vocabulary: 'flexible', meaning: 'adj.탄력적인, 구부리기 쉬운' },
    { vocabulary: 'contribute', meaning: 'v.기여하다, 공헌하다, (돈 등을)기부하다' },
    { vocabulary: 'part', meaning: 'n.일부,부품,역할' },
    { vocabulary: 'identical', meaning: 'adj.동일한, 일치하는' },
    { vocabulary: 'project', meaning: 'n.게획,설계,사업<br/>v.계획하다,추정하다' },
    { vocabulary: 'legal', meaning: 'adj.합법적인, 법률의' },
    { vocabulary: 'donate', meaning: 'v.기부하다,기증하다' },
    { vocabulary: 'receipt', meaning: 'n.영수증,수령,수취' },
    { vocabulary: 'moderate', meaning: 'adj.적당한,온건한' },
    { vocabulary: 'emphasize', meaning: 'v.강조하다' },
    { vocabulary: 'value', meaning: 'n.가치,가격,대가<br/>v.평가하다' },
    { vocabulary: 'rapid', meaning: 'adj.빠른,신속한' },
    { vocabulary: 'lack', meaning: 'n.부족,결핌<br/>v.모자라다,결핍하다' },
    { vocabulary: 'express', meaning: 'v.표현하다,나타내다<br/>n.(열차,버스등이ㅡ)급행, 속달우편' },
];
