export const vocabulariesTestRange = "범위: Day15 11번 - Day15 30번";
export const vocabularies = [
    { vocabulary: "tend", meaning: "v.~하는 경향이 있다, ~하기 쉽다" },
    { vocabulary: "assist", meaning: "v.돕다,조력하다<br/>n.조력,원조" },
    { vocabulary: "independent", meaning: "adj.독립의, 독자적인" },
    { vocabulary: "rent", meaning: "v.임대하다<br/>n.임대(료),집세" },
    { vocabulary: "consider", meaning: "v.고려하다,숙고하다" },
    { vocabulary: "satisfaction", meaning: "n.만족,충족" },
    { vocabulary: "internal", meaning: "adj.내부의,국내의" },
    { vocabulary: "dominate", meaning: "v.지배하다,(~보다) 우위를 차지하다" },
    { vocabulary: "session", meaning: "n.회의,학기" },
    { vocabulary: "persistent", meaning: "adj.끊임없는,계속되는" },
    { vocabulary: "specialty", meaning: "n.특기,특산품" },
    { vocabulary: "possible", meaning: "adj.가능한, 있음직한" },
    { vocabulary: "inspect", meaning: "v.면밀히 조사하다,검사하다" },
    { vocabulary: "survey", meaning: "n.설문 조사<br/>v.조사하다" },
    { vocabulary: "professional", meaning: "adj.전문적인,직업의<br/>n.전문가" },
    { vocabulary: "leave", meaning: "v.놓아두다, 떠나다<br/>n.휴가,허락" },
    { vocabulary: "term", meaning: "n.조건,기한,용어" },
    { vocabulary: "unused", meaning: "adj.사용하지 않는" },
    { vocabulary: "right", meaning: "n.권리, 소유권<br/>adv.바로, 곧" },
    { vocabulary: "inform", meaning: "v.알리다" },
];
