export const vocabulariesTestRange = "범위: Day14 21번 - Day15 10번";
export const vocabularies = [
    { vocabulary: "workplace", meaning: "일터, 작업장" },
    { vocabulary: "include", meaning: "포함하다" },
    { vocabulary: "remainder", meaning: "나머지" },
    { vocabulary: "practical", meaning: "현실적인, 적용 가능한" },
    { vocabulary: "justify", meaning: "정당화하다" },
    { vocabulary: "risk", meaning: "위험,모험<br/>위태롭게 하다" },
    { vocabulary: "unique", meaning: "독특한, 유일한" },
    { vocabulary: "method", meaning: "방법, 방식" },
    { vocabulary: "honored", meaning: "명예로운" },
    { vocabulary: "outdated", meaning: "구식의, 낡은" },
    { vocabulary: "ownership", meaning: "소유권" },
    { vocabulary: "critical", meaning: "비판적인, 결정적인" },
    { vocabulary: "separately", meaning: "개별적으로, 별도로" },
    { vocabulary: "stir", meaning: "휘젓다, 뒤섞다" },
    { vocabulary: "process", meaning: "과정,진행,경과<br/>가공(저장)하다" },
    { vocabulary: "domestic", meaning: "국내의,국산의,가정의" },
    { vocabulary: "seriously", meaning: "진지하게,심하게" },
    { vocabulary: "aim", meaning: "목표,목적<br/>겨누다" },
    { vocabulary: "productivity", meaning: "생산성" },
    { vocabulary: "financial", meaning: "재정의, 금전상의" },
];
