export const vocabulariesTestRange = "범위: Day12 01번 - Day12 20번";
export const vocabularies = [
  { vocabulary: 'credit', meaning: 'v.(계좌에) 돈을 입금하다, 믿다<br/>n.평판,명예' },
  { vocabulary: 'extra', meaning: 'adj.여분의, 추가의' },
  { vocabulary: 'fully', meaning: 'adv.충분히, 완전히' },
  { vocabulary: 'refuse', meaning: 'v.거절하다' },
  { vocabulary: 'factor', meaning: 'n.요소,원인' },
  { vocabulary: 'active', meaning: 'adj.적극적인, 활발한' },
  { vocabulary: 'politely', meaning: 'adv.공손히, 예의 바르게' },
  { vocabulary: 'acquire', meaning: 'v.매입하다, 취득하다' },
  { vocabulary: 'matter', meaning: 'n.문제<br/>v.중요하다' },
  { vocabulary: 'consistent', meaning: 'adj.시종 일관된' },
  { vocabulary: 'select', meaning: 'v.선택하다,고르다<br/>adj.고른,추려낸' },
  { vocabulary: 'appoint', meaning: 'v.지명하다, 임명하다' },
  { vocabulary: 'order', meaning: 'n.주문(품)<br/>v.주문하다' },
  { vocabulary: 'compare', meaning: 'v.비교하다,비유하다,필적하다' },
  { vocabulary: 'paycheck', meaning: 'n.급여' },
  { vocabulary: 'following', meaning: 'prep.~의 후에<br/>adj.다음의' },
  { vocabulary: 'differ', meaning: 'v.다르다,의견을 달리하다' },
  { vocabulary: 'rate', meaning: 'n.요금,비율<br/>v.평가하다,평가되다' },
  { vocabulary: 'industrial', meaning: 'adj.산업의' },
  { vocabulary: 'encourage', meaning: 'v.용기를 북돋우다,격려하다,촉진하다' },
]