export const vocabulariesTestRange = "범위: Day8 21번 - Day9 10번";
export const vocabularies = [
  { vocabulary: 'operation', meaning: 'n. 작용, 운행' },
  { vocabulary: 'lengthy', meaning: 'adj. 긴, 장황한' },
  { vocabulary: 'administer', meaning: 'v. 관리하다, 약을 투여하다' },
  { vocabulary: 'board', meaning: 'n.이사회<br/>v.탑승하다' },
  { vocabulary: 'noted', meaning: 'adj. 유명한, 주목할 만한' },
  { vocabulary: 'notify', meaning: 'v.통지하다, 알리다' },
  { vocabulary: 'competition', meaning: 'n. 경쟁, 경쟁 상대, 경기' },
  { vocabulary: 'document', meaning: 'n.서류,문서<br/>v.기록하다, 문서를 작성하다' },
  { vocabulary: 'apparently', meaning: 'adj.분명히, 명백히' },
  { vocabulary: 'helpful', meaning: 'adj.유익한, 편리한' },
  { vocabulary: 'slowdown', meaning: 'n. 경기 후퇴' },
  { vocabulary: 'suitable', meaning: 'adj.적합한, 적절한' },
  { vocabulary: 'efficient', meaning: 'adv. 효율적으로' },
  { vocabulary: 'describe', meaning: 'v. 말로 설명하다, 묘사하다' },
  { vocabulary: 'affordable', meaning: 'adj.(값이)알맞은, 구입할 수 있는' },
  { vocabulary: 'constantly', meaning: 'adv.끊임없이, 항상' },
  { vocabulary: 'announce', meaning: 'v.알리다, 공고하다' },
  { vocabulary: 'aspect', meaning: 'n.관점, 양상' },
  { vocabulary: 'eventually', meaning: 'adv. 결국, 마침내' },
  { vocabulary: 'consult', meaning: 'v. 상담하다, 상의하다' },
]