export const vocabulariesTestRange = "범위: Day12 21번 - Day13 10번";
export const vocabularies = [
  { vocabulary: 'likely', meaning: 'adj.~할 것같은, 있음 직한<br/>adv.아마' },
  { vocabulary: 'feature', meaning: 'v.특색으로 삼다, 특징을 이루다<br/>n.특징,특색' },
  { vocabulary: 'wage', meaning: 'n.임금,급료' },
  { vocabulary: 'mounting', meaning: 'adj.증가하는,오르는' },
  { vocabulary: 'halt', meaning: 'n.중단,정지<br/>v.정지시키다' },
  { vocabulary: 'reference', meaning: 'n.참조,참고,추천서' },
  { vocabulary: 'realistic', meaning: 'adj.현실적인' },
  { vocabulary: 'elected', meaning: 'adj.선출된' },
  { vocabulary: 'worsen', meaning: 'v.악화시키다,악화되다' },
  { vocabulary: 'translation', meaning: 'n.번역,해석' },
  { vocabulary: 'currency', meaning: 'n.화폐,통화,유통' },
  { vocabulary: 'annual', meaning: 'adj.매년의,해마다의' },
  { vocabulary: 'poorly', meaning: 'adv.부족하게,서툴게' },
  { vocabulary: 'remind', meaning: 'v.상기시키다, 일깨우다' },
  { vocabulary: 'finding', meaning: '(보통 pl.)조사 결과, 발견' },
  { vocabulary: 'continuous', meaning: 'adj.계속되는, 지속적인' },
  { vocabulary: 'randomly', meaning: 'adv.무작위로,임의로' },
  { vocabulary: 'admit', meaning: 'v.(사람,사물을)들이다, 인정하다' },
  { vocabulary: 'maximum', meaning: 'adj.최대한의,n.최대' },
  { vocabulary: 'demand', meaning: 'n.요청,요구,수요<br/>v.요구하다' },
]